"""Create Unit table

Revision ID: 0e0d8dc1293d
Revises: ad1167413ea1
Create Date: 2026-07-14 16:34:10.204994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0d8dc1293d'
down_revision: Union[str, Sequence[str], None] = 'ad1167413ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('unit_type', sa.String(length=30), nullable=False))
    op.add_column('units', sa.Column('owner_name', sa.String(length=100), nullable=True))
    op.add_column('units', sa.Column('intercom_number', sa.String(length=20), nullable=True))
    op.add_column('units', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('units', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('units', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('units', 'occupancy_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('units', 'occupancy_status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('units', 'updated_at')
    op.drop_column('units', 'created_at')
    op.drop_column('units', 'is_active')
    op.drop_column('units', 'intercom_number')
    op.drop_column('units', 'owner_name')
    op.drop_column('units', 'unit_type')
    # ### end Alembic commands ###
