"""add unique property organization name

Revision ID: 1a13529bff87
Revises: e00fc9a4bba7
Create Date: 2026-07-22 14:11:09.212848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a13529bff87'
down_revision: Union[str, Sequence[str], None] = 'e00fc9a4bba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_property_organization_name', 'properties', ['organization_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_property_organization_name', 'properties', type_='unique')
    # ### end Alembic commands ###
