"""Improve resident constraints

Revision ID: 260c77d66022
Revises: f18550df1320
Create Date: 2026-07-21 00:42:53.071652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260c77d66022'
down_revision: Union[str, Sequence[str], None] = 'f18550df1320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_resident_email', 'residents', ['email'], unique=False)
    op.create_index('ix_resident_phone', 'residents', ['phone'], unique=False)
    op.create_index('ix_resident_unit_id', 'residents', ['unit_id'], unique=False)
    op.create_index(op.f('ix_residents_unit_id'), 'residents', ['unit_id'], unique=False)
    op.create_unique_constraint(None, 'residents', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'residents', type_='unique')
    op.drop_index(op.f('ix_residents_unit_id'), table_name='residents')
    op.drop_index('ix_resident_unit_id', table_name='residents')
    op.drop_index('ix_resident_phone', table_name='residents')
    op.drop_index('ix_resident_email', table_name='residents')
    # ### end Alembic commands ###
