"""add updated_at to deliveries

Revision ID: 2e0d73c5f0f5
Revises: 5b3dd8e13cdd
Create Date: 2026-07-21 13:58:13.893395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0d73c5f0f5'
down_revision: Union[str, Sequence[str], None] = '5b3dd8e13cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_deliveries_collected_at'), 'deliveries', ['collected_at'], unique=False)
    op.create_index(op.f('ix_deliveries_created_at'), 'deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_deliveries_delivery_category'), 'deliveries', ['delivery_category'], unique=False)
    op.create_index(op.f('ix_deliveries_priority'), 'deliveries', ['priority'], unique=False)
    op.create_index(op.f('ix_deliveries_resident_id'), 'deliveries', ['resident_id'], unique=False)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_deliveries_tracking_number'), 'deliveries', ['tracking_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliveries_tracking_number'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_resident_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_priority'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_delivery_category'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_created_at'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_collected_at'), table_name='deliveries')
    op.drop_column('deliveries', 'updated_at')
    # ### end Alembic commands ###
