"""Authentication and RBAC cleanup

Revision ID: 396abaed29e9
Revises: 5cea08ea8467
Create Date: 2026-07-21 02:06:54.365262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396abaed29e9'
down_revision: Union[str, Sequence[str], None] = '5cea08ea8467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
