"""add_has_multiple_sections

Revision ID: 4af4ba7b7d61
Revises: 063e2ac854ef
Create Date: 2026-07-24 14:51:16.650016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af4ba7b7d61'
down_revision: Union[str, Sequence[str], None] = '063e2ac854ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('has_multiple_sections', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'has_multiple_sections')
    # ### end Alembic commands ###
