"""Add visitor indexes and updated_at

Revision ID: 5b3dd8e13cdd
Revises: 98157a75cda0
Create Date: 2026-07-21 12:02:52.925188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision: str = '5b3dd8e13cdd'
down_revision: Union[str, Sequence[str], None] = '98157a75cda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "visitors",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=func.now(),
        ),
    )

    op.alter_column(
        "visitors",
        "updated_at",
        server_default=None,
    )

    op.create_index(op.f("ix_visitors_check_in_time"), "visitors", ["check_in_time"], unique=False)
    op.create_index(op.f("ix_visitors_created_at"), "visitors", ["created_at"], unique=False)
    op.create_index(op.f("ix_visitors_phone"), "visitors", ["phone"], unique=False)
    op.create_index(op.f("ix_visitors_resident_id"), "visitors", ["resident_id"], unique=False)
    op.create_index(op.f("ix_visitors_status"), "visitors", ["status"], unique=False)
    op.create_index(op.f("ix_visitors_vehicle_number"), "visitors", ["vehicle_number"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitors_vehicle_number'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_status'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_resident_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_phone'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_created_at'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_check_in_time'), table_name='visitors')
    op.drop_column('visitors', 'updated_at')
    # ### end Alembic commands ###
