"""add join request table

Revision ID: 7e833b71b6a3
Revises: d656f9fff766
Create Date: 2026-07-22 14:42:07.295218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e833b71b6a3'
down_revision: Union[str, Sequence[str], None] = 'd656f9fff766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('requested_unit_id', sa.Integer(), nullable=True),
    sa.Column('assigned_unit_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='joinstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('sections_property_id_fkey'), 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('units_property_id_fkey'), 'units', type_='foreignkey')
    op.drop_constraint(op.f('units_section_id_fkey'), 'units', type_='foreignkey')
    op.create_foreign_key(None, 'units', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'units', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.create_foreign_key(op.f('units_section_id_fkey'), 'units', 'sections', ['section_id'], ['id'])
    op.create_foreign_key(op.f('units_property_id_fkey'), 'units', 'properties', ['property_id'], ['id'])
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_foreign_key(op.f('sections_property_id_fkey'), 'sections', 'properties', ['property_id'], ['id'])
    op.drop_table('join_requests')
    # ### end Alembic commands ###
