"""Add QR fields to visitor

Revision ID: 92c938f9cdc3
Revises: 7fa1775a0ee9
Create Date: 2026-07-14 19:37:35.987043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c938f9cdc3'
down_revision: Union[str, Sequence[str], None] = '7fa1775a0ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('qr_token', sa.String(length=100), nullable=True))
    op.add_column('visitors', sa.Column('qr_code', sa.String(length=255), nullable=True))
    op.add_column('visitors', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'visitors', ['qr_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitors', type_='unique')
    op.drop_column('visitors', 'approved_at')
    op.drop_column('visitors', 'qr_code')
    op.drop_column('visitors', 'qr_token')
    # ### end Alembic commands ###
