"""Add vehicle indexes

Revision ID: 98157a75cda0
Revises: d6e238358824
Create Date: 2026-07-21 11:50:09.121230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98157a75cda0'
down_revision: Union[str, Sequence[str], None] = 'd6e238358824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vehicles_vehicle_number_key'), 'vehicles', type_='unique')
    op.create_index(op.f('ix_vehicles_created_at'), 'vehicles', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehicles_is_active'), 'vehicles', ['is_active'], unique=False)
    op.create_index(op.f('ix_vehicles_resident_id'), 'vehicles', ['resident_id'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_number'), 'vehicles', ['vehicle_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_vehicle_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_resident_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_is_active'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_created_at'), table_name='vehicles')
    op.create_unique_constraint(op.f('vehicles_vehicle_number_key'), 'vehicles', ['vehicle_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
