"""add organization code

Revision ID: add7b25baf24
Revises: a9c068a2c351
Create Date: 2026-07-22 19:29:47.859940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add7b25baf24'
down_revision: Union[str, Sequence[str], None] = 'a9c068a2c351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=150), nullable=False),
    sa.Column('organization_type', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_applications_email'), 'organization_applications', ['email'], unique=False)
    op.create_index(op.f('ix_organization_applications_id'), 'organization_applications', ['id'], unique=False)
    op.create_index(op.f('ix_organization_applications_phone'), 'organization_applications', ['phone'], unique=False)
    op.create_index(op.f('ix_organization_applications_status'), 'organization_applications', ['status'], unique=False)
    op.add_column('organizations', sa.Column('organization_code', sa.String(length=20), nullable=False))
    op.add_column('organizations', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('organizations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_organizations_organization_code'), 'organizations', ['organization_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_organization_code'), table_name='organizations')
    op.drop_column('organizations', 'updated_at')
    op.drop_column('organizations', 'created_at')
    op.drop_column('organizations', 'is_active')
    op.drop_column('organizations', 'organization_code')
    op.drop_index(op.f('ix_organization_applications_status'), table_name='organization_applications')
    op.drop_index(op.f('ix_organization_applications_phone'), table_name='organization_applications')
    op.drop_index(op.f('ix_organization_applications_id'), table_name='organization_applications')
    op.drop_index(op.f('ix_organization_applications_email'), table_name='organization_applications')
    op.drop_table('organization_applications')
    # ### end Alembic commands ###
