"""Add section unique constraint

Revision ID: b8cd98a37214
Revises: 35cc9c2c3d0d
Create Date: 2026-07-21 00:11:10.726928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8cd98a37214'
down_revision: Union[str, Sequence[str], None] = '35cc9c2c3d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sections_property_id'), 'sections', ['property_id'], unique=False)
    op.create_unique_constraint('uq_property_section_name', 'sections', ['property_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_property_section_name', 'sections', type_='unique')
    op.drop_index(op.f('ix_sections_property_id'), table_name='sections')
    # ### end Alembic commands ###
