"""Improve unit constraints

Revision ID: f18550df1320
Revises: b607ee43c732
Create Date: 2026-07-21 00:19:48.284584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18550df1320'
down_revision: Union[str, Sequence[str], None] = 'b607ee43c732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_units_property_id'), 'units', ['property_id'], unique=False)
    op.create_index(op.f('ix_units_section_id'), 'units', ['section_id'], unique=False)
    op.create_unique_constraint('uq_section_unit_number', 'units', ['section_id', 'unit_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_section_unit_number', 'units', type_='unique')
    op.drop_index(op.f('ix_units_section_id'), table_name='units')
    op.drop_index(op.f('ix_units_property_id'), table_name='units')
    # ### end Alembic commands ###
