from enum import Enum


class UserRole(str, Enum):
    SYSTEM_ADMIN = "SYSTEM_ADMIN"
    ORGANIZATION_ADMIN = "ORGANIZATION_ADMIN"
    PROPERTY_MANAGER = "PROPERTY_MANAGER"
    SECURITY_MANAGER = "SECURITY_MANAGER"
    SECURITY_GUARD = "SECURITY_GUARD"
    RESIDENT = "RESIDENT"